### ISSUE TITLE
Value not saved when used as a templatefield

### ISSUE THREAD

**Issue by Ninimoon** [Raistlfiren/FAIconFieldType#3]
Hi,

I just installed your awesome extension. It works fine when I use it as a "normal" field. But I would like to use it as a Templatefield. When I do so, it does appear on the edit page but the value is not saved in database (sqlite). It just shows me a empty value ("").

Did you try it this way ? Do you have an idea about where the problem could come from ?

Thanks.

**Comment by Raistlfiren** [comment]
Ninimoon,

I just tried adding a template field on a fresh install, and was able to replicate the issue you were encountering. Currently, template fields are being heavily revised in the core of Bolt, and there is not a good way of handling the field type. I could create a hack for it, but I would have to revise it in the near future. 

This isn't the best way of doing this, but I create a widgets content type and just display the unique content on the page.
