### ISSUE TITLE
type: repeater // does not work

### ISSUE THREAD

**Issue by steiha** [Raistlfiren/FAIconFieldType#5]
Breaks the admin panel if this field type is used inside repeater.

I tried to fix it, maybe I can do a pull request later.

If I remove the script tag from the twig template the admin panel works (of course the fa icon picker not)

This way it could probably be fixed:
- add a new launcher js file e.g. start.js (https://docs.bolt.cm/3.0/extensions/advanced/customfields)
- remove script tag from twig template (_faiconpicker.twig) and move js code to start.js
- template needs some tweaks as well
- pass configs as data attributes

**Comment by Raistlfiren** [comment]
I looked into this tonight, and it does seem like there is a bug with the repeating fields. I will see if I can't implement something better in the next few days through data attributes. Although, it is kind of a hack. Thanks for reporting this @steiha!

**Comment by steiha** [comment]
Just found that the repeater uses script tags to add template snippets to the source:

`<script type="text/template">
    <div class="repeater-group row panel panel-default">
        [...]
    </div>
</script>`

So if there are other script-tags inside it is all messed up.
http://stackoverflow.com/questions/14261232/including-script-tag-in-script-type-text-template-tag

**Comment by Raistlfiren** [comment]
@steiha Thanks for reporting this. I have updated the code to now fix this problem with repeating fields. (Release V3.3) Configuration is now stored as a data attribute. I am closing this issue. If you have a similar problem, feel free to open a new issue.

Cheers!

Aaron
