### ISSUE TITLE
Some quirks

### ISSUE THREAD

**Issue by steiha** [Raistlfiren/FAIconFieldType#6]
Just tried with the latest bolt release (3.0.11 ), there seem to be some issues.
- type in filter does not work
- no preview of selected icon
- raises js error on focus (with stored value) 
  e.g. "Uncaught Error: Syntax error, unrecognized expression: .fa..fa-automobile"

tested with safari and chrome on Mac OS X (10.11.6)

**Comment by Raistlfiren** [comment]
@steiha That is weird the filter isn't working. I will have to look at that tonight.

**no preview of selected icon** - Add `component: true` under the field type and it should display the icon right next to the input box.

**raises js error on focus** - I will look into this tonight as well.

Thanks!

**Comment by Raistlfiren** [comment]
I believe most of these issues are fixed, but there are problems with repeating fields that need to be solved in the Bolt master branch. Version 3.4 should include the correct fixes.

**Comment by steiha** [comment]
Thank you for looking into it. Sorry to say but the filter still does not work for me. Well not that important.

**Comment by Raistlfiren** [comment]
@steiha Sorry for the slow response. I did a fresh install of bolt3 with the extension and it seemed to work. Make sure you have the correct assets loaded. You can verify by opening up `js/fontawesome-iconpicker.js` and check for line `554` to have `this.getSearchInput().on("keyup", function()`.

Thanks!

**Comment by steiha** [comment]
I did a fresh install, and the filter is working. So I think you were right I was still using an stale cached version. Thank you.
